# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Qt/HMI/insertreason.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_insertReason(object):
    def setupUi(self, insertReason):
        insertReason.setObjectName("insertReason")
        insertReason.setEnabled(True)
        insertReason.resize(500, 370)
        insertReason.setStyleSheet("")
        self.label = QtWidgets.QLabel(insertReason)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 500, 320))
        self.label.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pb_submit = QtWidgets.QPushButton(insertReason)
        self.pb_submit.setGeometry(QtCore.QRect(0, 320, 500, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_submit.setFont(font)
        self.pb_submit.setStyleSheet("background-color: rgb(255, 208, 35);\n"
"color: rgb(255, 255, 255);")
        self.pb_submit.setAutoDefault(False)
        self.pb_submit.setDefault(False)
        self.pb_submit.setFlat(False)
        self.pb_submit.setObjectName("pb_submit")
        self.label_2 = QtWidgets.QLabel(insertReason)
        self.label_2.setGeometry(QtCore.QRect(165, 10, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pb_close = QtWidgets.QPushButton(insertReason)
        self.pb_close.setGeometry(QtCore.QRect(450, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pb_close.setFont(font)
        self.pb_close.setStyleSheet("background-color: rgb(225, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pb_close.setObjectName("pb_close")
        self.label_3 = QtWidgets.QLabel(insertReason)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 85, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(insertReason)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 85, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(insertReason)
        self.label_6.setGeometry(QtCore.QRect(40, 180, 85, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(insertReason)
        self.label_7.setGeometry(QtCore.QRect(130, 120, 5, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(insertReason)
        self.label_8.setGeometry(QtCore.QRect(130, 250, 5, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(insertReason)
        self.label_9.setGeometry(QtCore.QRect(130, 180, 5, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cb_mesin = QtWidgets.QComboBox(insertReason)
        self.cb_mesin.setGeometry(QtCore.QRect(150, 120, 300, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cb_mesin.setFont(font)
        self.cb_mesin.setObjectName("cb_mesin")
        self.cb_mesin.addItem("")
        self.cb_mesin.addItem("")
        self.cb_mesin.addItem("")
        self.cb_mesin.addItem("")
        self.cb_kategori = QtWidgets.QComboBox(insertReason)
        self.cb_kategori.setGeometry(QtCore.QRect(150, 180, 300, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cb_kategori.setFont(font)
        self.cb_kategori.setObjectName("cb_kategori")
        self.cb_kategori.addItem("")
        self.cb_kategori.addItem("")
        self.cb_alasan = QtWidgets.QComboBox(insertReason)
        self.cb_alasan.setGeometry(QtCore.QRect(150, 250, 300, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cb_alasan.setFont(font)
        self.cb_alasan.setStyleSheet("color: rgb(255, 0, 0);")
        self.cb_alasan.setObjectName("cb_alasan")
        self.cb_alasan.addItem("")
        self.cb_alasan.addItem("")
        self.lbl_date = QtWidgets.QLabel(insertReason)
        self.lbl_date.setGeometry(QtCore.QRect(150, 45, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_date.setFont(font)
        self.lbl_date.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_date.setObjectName("lbl_date")
        self.lbl_time = QtWidgets.QLabel(insertReason)
        self.lbl_time.setGeometry(QtCore.QRect(250, 45, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_time.setFont(font)
        self.lbl_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_duration = QtWidgets.QLabel(insertReason)
        self.lbl_duration.setGeometry(QtCore.QRect(200, 70, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_duration.setFont(font)
        self.lbl_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_duration.setObjectName("lbl_duration")
        self.label_12 = QtWidgets.QLabel(insertReason)
        self.label_12.setGeometry(QtCore.QRect(240, 45, 10, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(insertReason)
        QtCore.QMetaObject.connectSlotsByName(insertReason)

    def retranslateUi(self, insertReason):
        _translate = QtCore.QCoreApplication.translate
        insertReason.setWindowTitle(_translate("insertReason", "Form"))
        self.pb_submit.setText(_translate("insertReason", "SUBMIT"))
        self.label_2.setText(_translate("insertReason", "Downtime"))
        self.pb_close.setText(_translate("insertReason", "X"))
        self.label_3.setText(_translate("insertReason", "Mesin"))
        self.label_5.setText(_translate("insertReason", "Alasan"))
        self.label_6.setText(_translate("insertReason", "Kategori"))
        self.label_7.setText(_translate("insertReason", ":"))
        self.label_8.setText(_translate("insertReason", ":"))
        self.label_9.setText(_translate("insertReason", ":"))
        self.cb_mesin.setItemText(0, _translate("insertReason", "Packing 1"))
        self.cb_mesin.setItemText(1, _translate("insertReason", "Packing 2"))
        self.cb_mesin.setItemText(2, _translate("insertReason", "Packing 3"))
        self.cb_mesin.setItemText(3, _translate("insertReason", "Packing 4"))
        self.cb_kategori.setItemText(0, _translate("insertReason", "Unplanned Downtime (UPDT)"))
        self.cb_kategori.setItemText(1, _translate("insertReason", "Planned Downtime"))
        self.cb_alasan.setItemText(0, _translate("insertReason", "Gear Patah"))
        self.cb_alasan.setItemText(1, _translate("insertReason", "Mesin Mati"))
        self.lbl_date.setText(_translate("insertReason", "1-Jun-2018"))
        self.lbl_time.setText(_translate("insertReason", "9:00:05"))
        self.lbl_duration.setText(_translate("insertReason", "{00:15:00}"))
        self.label_12.setText(_translate("insertReason", "|"))

