# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Qt/HMI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pb_logout = QtWidgets.QPushButton(self.centralWidget)
        self.pb_logout.setGeometry(QtCore.QRect(50, 20, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_logout.setFont(font)
        self.pb_logout.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.pb_logout.setObjectName("pb_logout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 233, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(283, 110, 233, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(515, 110, 233, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(50, 151, 700, 280))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(100, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(100, 240, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(100, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(100, 380, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lbl_status_1 = QtWidgets.QLabel(self.centralWidget)
        self.lbl_status_1.setGeometry(QtCore.QRect(360, 170, 100, 20))
        self.lbl_status_1.setStyleSheet("background-color: rgb(0, 199, 0);")
        self.lbl_status_1.setText("")
        self.lbl_status_1.setObjectName("lbl_status_1")
        self.lbl_status_2 = QtWidgets.QLabel(self.centralWidget)
        self.lbl_status_2.setGeometry(QtCore.QRect(360, 240, 100, 20))
        self.lbl_status_2.setStyleSheet("background-color: rgb(0, 199, 0);")
        self.lbl_status_2.setText("")
        self.lbl_status_2.setObjectName("lbl_status_2")
        self.lbl_status_3 = QtWidgets.QLabel(self.centralWidget)
        self.lbl_status_3.setGeometry(QtCore.QRect(360, 310, 100, 20))
        self.lbl_status_3.setStyleSheet("background-color: rgb(0, 199, 0);")
        self.lbl_status_3.setText("")
        self.lbl_status_3.setObjectName("lbl_status_3")
        self.lbl_status_4 = QtWidgets.QLabel(self.centralWidget)
        self.lbl_status_4.setGeometry(QtCore.QRect(360, 380, 100, 20))
        self.lbl_status_4.setStyleSheet("background-color: rgb(0, 199, 0);")
        self.lbl_status_4.setText("")
        self.lbl_status_4.setObjectName("lbl_status_4")
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(519, 20, 231, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(650, 60, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.lw_reason = QtWidgets.QListWidget(self.centralWidget)
        self.lw_reason.setGeometry(QtCore.QRect(500, 170, 231, 241))
        self.lw_reason.setObjectName("lw_reason")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_logout.setText(_translate("MainWindow", "Logout"))
        self.label.setText(_translate("MainWindow", "MF Alfafa"))
        self.label_2.setText(_translate("MainWindow", "Mesin"))
        self.label_3.setText(_translate("MainWindow", "Status"))
        self.label_4.setText(_translate("MainWindow", "Antrian"))
        self.label_6.setText(_translate("MainWindow", "Packaging 1"))
        self.label_7.setText(_translate("MainWindow", "Packaging 2"))
        self.label_8.setText(_translate("MainWindow", "Packaging 3"))
        self.label_9.setText(_translate("MainWindow", "Packaging 4"))
        self.label_14.setText(_translate("MainWindow", "HMI Packaging Line 23"))
        self.label_15.setText(_translate("MainWindow", "08:35"))

